const path = require(`path`)
const { createRemoteFileNode } = require("gatsby-source-filesystem")
const { error } = require("console")

exports.createPages = async ({ graphql, actions }) => {
  const { createPage } = actions

  const allCategories = await graphql(`
    query SiteNavQuery {
      allStrapiCategory(
        filter: {
          games: {
            elemMatch: {
              appid: {
                in: [
                  "BigSword"
                  "BoardTheTrain"
                  "FireTheGun"
                  "MergeGuns3D"
                  "FeverRacing"
                  "ColorBall3D"
                  "ZombieSurvival"
                  "CrazyMoto"
                  "CrazyKart3D"
                  "LetMeIn"
                  "BumbleShooter"
                  "Knife"
                  "HiTaxi"
                  "TrafficRun"
                  "BulletMaster3D"
                  "MrRacer"
                  "MagicParkour"
                  "FrozenMagic"
                  "MrBullet"
                  "JumpSmash"
                  "CrazyKnife"
                  "TrafficPassing"
                  "SuperThrow"
                  "AceMan"
                  "BatterKing"
                  "GoldenGlove"
                  "KnockBalls"
                  "CrashTower3D"
                  "DragonCrush"
                  "HungryAnimals"
                  "SnakeGo"
                  "DessertConnect"
                  "SwiftRider"
                  "CrackShot"
                  "CrazyGunfight"
                  "ColorRing"
                  "PianoKeys"
                  "ArchersKing"
                  "MyBabyCare"
                  "DartsKing3D"
                  "CrazyRace"
                  "BallIsComing"
                  "HungyBunny"
                  "TheSameWorld"
                  "SuperMiner"
                  "BounceShooter"
                  "HillRacing"
                  "BlockGun3D"
                  "FruitMonster"
                  "FierceCity"
                  "IronAttack"
                  "AirBrawl"
                  "AmazingRoad"
                  "RainbowSplash"
                  "CrazyDrift"
                  "FruitsFall"
                  "RocketJump"
                  "MagicPaint"
                  "GlidingCharger"
                  "RoadCharger"
                  "ArcheryMaster"
                  "UltraDrift"
                  "SharkIsComing"
                  "PuppyRun"
                  "PenguinDash"
                  "MonsterCrash"
                  "DeathJump"
                  "HungryMonster"
                  "JumpingMonkey"
                  "MergeKill"
                  "CrazyTrain3D"
                  "CrazyHammer"
                  "VirusWar"
                  "TrappedPirate"
                  "StickmanVsZombies"
                  "FingerCannon"
                  "BulletMan"
                  "GunShooter"
                  "TowerBlast3D"
                  "ShootSmash"
                  "ShootingCubes"
                  "BubbleBlast"
                  "FlyPass"
                  "KillAllZombies"
                  "CollectColorfulBalls"
                  "KimbapRun"
                  "AnipopLink"
                  "PetsMatch"
                  "HappyBilliards"
                  "CrazyBomb"
                  "HelpTheZombie"
                  "SaveThePets"
                  "SoccerHero"
                  "TableTennisChampionship"
                  "MagicDonuts"
                  "SolitaireClassic"
                  "DeathRun"
                  "IdleRestaurantTycoon"
                  "ImEmpire"
                  "MahjongConnect"
                  "MiningMaster"
                  "Transform"
                  "DefenseTower"
                  "TwistyRoad"
                  "ZooBlast"
                  "ZumaMarbles"
                  "BlockPuzzle"
                  "CrazyPortal"
                  "DressQueen"
                  "MahjongLink3D"
                  "MergeAndDefense"
                  "MergeMagicJewellery"
                  "PetRun"
                  "SkyRunning3D"
                  "SuperGolf"
                  "TowerDefenseX"
                  "PandaRescue"
                  "FillTheGlass"
                  "MagicNumber"
                  "PlantBeatZombies"
                  "AirHockey3D"
                  "MyBowling3D"
                  "Chess3D"
                  "8BallKing"
                  "MyUnicorn"
                  "MagicJigsaw"
                  "FairyTalesPuzzle"
                  "PipePuzzle"
                  "SplittingCells"
                  "FeedMaster"
                  "FinalBattle"
                  "SuperDefense"
                  "Super2048"
                  "BubblePop"
                  "RelivedLife"
                  "CandyHit"
                  "MergeCat"
                  "MelodyLink"
                  "PuzzleVenture"
                  "BrainMaster"
                  "AntRun"
                  "BombingTime"
                  "BlockMaze"
                  "HappyTetris"
                  "MagicPainter"
                  "MatchingCook"
                  "ColorBead"
                  "ColorSplash"
                  "RollingAgent"
                  "RushingRover"
                ]
              }
            }
          }
        }
      ) {
        nodes {
          name
          slug
        }
      }
    }
  `)

  const gamesDataDetail = await graphql(`
    query SiteNavQuery {
      allStrapiGame(
        sort: { fields: creation_date, order: DESC }
        filter: {
          appid: {
            in: [
              "BigSword"
              "BoardTheTrain"
              "FireTheGun"
              "MergeGuns3D"
              "FeverRacing"
              "ColorBall3D"
              "ZombieSurvival"
              "CrazyMoto"
              "CrazyKart3D"
              "LetMeIn"
              "BumbleShooter"
              "Knife"
              "HiTaxi"
              "TrafficRun"
              "BulletMaster3D"
              "MrRacer"
              "MagicParkour"
              "FrozenMagic"
              "MrBullet"
              "JumpSmash"
              "CrazyKnife"
              "TrafficPassing"
              "SuperThrow"
              "AceMan"
              "BatterKing"
              "GoldenGlove"
              "KnockBalls"
              "CrashTower3D"
              "DragonCrush"
              "HungryAnimals"
              "SnakeGo"
              "DessertConnect"
              "SwiftRider"
              "CrackShot"
              "CrazyGunfight"
              "ColorRing"
              "PianoKeys"
              "ArchersKing"
              "MyBabyCare"
              "DartsKing3D"
              "CrazyRace"
              "BallIsComing"
              "HungyBunny"
              "TheSameWorld"
              "SuperMiner"
              "BounceShooter"
              "HillRacing"
              "BlockGun3D"
              "FruitMonster"
              "FierceCity"
              "IronAttack"
              "AirBrawl"
              "AmazingRoad"
              "RainbowSplash"
              "CrazyDrift"
              "FruitsFall"
              "RocketJump"
              "MagicPaint"
              "GlidingCharger"
              "RoadCharger"
              "ArcheryMaster"
              "UltraDrift"
              "SharkIsComing"
              "PuppyRun"
              "PenguinDash"
              "MonsterCrash"
              "DeathJump"
              "HungryMonster"
              "JumpingMonkey"
              "MergeKill"
              "CrazyTrain3D"
              "CrazyHammer"
              "VirusWar"
              "TrappedPirate"
              "StickmanVsZombies"
              "FingerCannon"
              "BulletMan"
              "GunShooter"
              "TowerBlast3D"
              "ShootSmash"
              "ShootingCubes"
              "BubbleBlast"
              "FlyPass"
              "KillAllZombies"
              "CollectColorfulBalls"
              "KimbapRun"
              "AnipopLink"
              "PetsMatch"
              "HappyBilliards"
              "CrazyBomb"
              "HelpTheZombie"
              "SaveThePets"
              "SoccerHero"
              "TableTennisChampionship"
              "MagicDonuts"
              "SolitaireClassic"
              "DeathRun"
              "IdleRestaurantTycoon"
              "ImEmpire"
              "MahjongConnect"
              "MiningMaster"
              "Transform"
              "DefenseTower"
              "TwistyRoad"
              "ZooBlast"
              "ZumaMarbles"
              "BlockPuzzle"
              "CrazyPortal"
              "DressQueen"
              "MahjongLink3D"
              "MergeAndDefense"
              "MergeMagicJewellery"
              "PetRun"
              "SkyRunning3D"
              "SuperGolf"
              "TowerDefenseX"
              "PandaRescue"
              "FillTheGlass"
              "MagicNumber"
              "PlantBeatZombies"
              "AirHockey3D"
              "MyBowling3D"
              "Chess3D"
              "8BallKing"
              "MyUnicorn"
              "MagicJigsaw"
              "FairyTalesPuzzle"
              "PipePuzzle"
              "SplittingCells"
              "FeedMaster"
              "FinalBattle"
              "SuperDefense"
              "Super2048"
              "BubblePop"
              "RelivedLife"
              "CandyHit"
              "MergeCat"
              "MelodyLink"
              "PuzzleVenture"
              "BrainMaster"
              "AntRun"
              "BombingTime"
              "BlockMaze"
              "HappyTetris"
              "MagicPainter"
              "MatchingCook"
              "ColorBead"
              "ColorSplash"
              "RollingAgent"
              "RushingRover"
            ]
          }
        }
      ) {
        nodes {
          slug
          gid
          appid
        }
      }
    }
  `)

  const gamesDataCategory = await graphql(`
    query SiteNavQuery {
      allStrapiGame(
        sort: { fields: creation_date, order: DESC }
        filter: {
          appid: {
            in: [
              "BigSword"
              "BoardTheTrain"
              "FireTheGun"
              "MergeGuns3D"
              "FeverRacing"
              "ColorBall3D"
              "ZombieSurvival"
              "CrazyMoto"
              "CrazyKart3D"
              "LetMeIn"
              "BumbleShooter"
              "Knife"
              "HiTaxi"
              "TrafficRun"
              "BulletMaster3D"
              "MrRacer"
              "MagicParkour"
              "FrozenMagic"
              "MrBullet"
              "JumpSmash"
              "CrazyKnife"
              "TrafficPassing"
              "SuperThrow"
              "AceMan"
              "BatterKing"
              "GoldenGlove"
              "KnockBalls"
              "CrashTower3D"
              "DragonCrush"
              "HungryAnimals"
              "SnakeGo"
              "DessertConnect"
              "SwiftRider"
              "CrackShot"
              "CrazyGunfight"
              "ColorRing"
              "PianoKeys"
              "ArchersKing"
              "MyBabyCare"
              "DartsKing3D"
              "CrazyRace"
              "BallIsComing"
              "HungyBunny"
              "TheSameWorld"
              "SuperMiner"
              "BounceShooter"
              "HillRacing"
              "BlockGun3D"
              "FruitMonster"
              "FierceCity"
              "IronAttack"
              "AirBrawl"
              "AmazingRoad"
              "RainbowSplash"
              "CrazyDrift"
              "FruitsFall"
              "RocketJump"
              "MagicPaint"
              "GlidingCharger"
              "RoadCharger"
              "ArcheryMaster"
              "UltraDrift"
              "SharkIsComing"
              "PuppyRun"
              "PenguinDash"
              "MonsterCrash"
              "DeathJump"
              "HungryMonster"
              "JumpingMonkey"
              "MergeKill"
              "CrazyTrain3D"
              "CrazyHammer"
              "VirusWar"
              "TrappedPirate"
              "StickmanVsZombies"
              "FingerCannon"
              "BulletMan"
              "GunShooter"
              "TowerBlast3D"
              "ShootSmash"
              "ShootingCubes"
              "BubbleBlast"
              "FlyPass"
              "KillAllZombies"
              "CollectColorfulBalls"
              "KimbapRun"
              "AnipopLink"
              "PetsMatch"
              "HappyBilliards"
              "CrazyBomb"
              "HelpTheZombie"
              "SaveThePets"
              "SoccerHero"
              "TableTennisChampionship"
              "MagicDonuts"
              "SolitaireClassic"
              "DeathRun"
              "IdleRestaurantTycoon"
              "ImEmpire"
              "MahjongConnect"
              "MiningMaster"
              "Transform"
              "DefenseTower"
              "TwistyRoad"
              "ZooBlast"
              "ZumaMarbles"
              "BlockPuzzle"
              "CrazyPortal"
              "DressQueen"
              "MahjongLink3D"
              "MergeAndDefense"
              "MergeMagicJewellery"
              "PetRun"
              "SkyRunning3D"
              "SuperGolf"
              "TowerDefenseX"
              "PandaRescue"
              "FillTheGlass"
              "MagicNumber"
              "PlantBeatZombies"
              "AirHockey3D"
              "MyBowling3D"
              "Chess3D"
              "8BallKing"
              "MyUnicorn"
              "MagicJigsaw"
              "FairyTalesPuzzle"
              "PipePuzzle"
              "SplittingCells"
              "FeedMaster"
              "FinalBattle"
              "SuperDefense"
              "Super2048"
              "BubblePop"
              "RelivedLife"
              "CandyHit"
              "MergeCat"
              "MelodyLink"
              "PuzzleVenture"
              "BrainMaster"
              "AntRun"
              "BombingTime"
              "BlockMaze"
              "HappyTetris"
              "MagicPainter"
              "MatchingCook"
              "ColorBead"
              "ColorSplash"
              "RollingAgent"
              "RushingRover"
            ]
          }
        }
      ) {
        nodes {
          icon_url
          title
          slug
          gid
          appid
          category {
            slug
            name
          }
        }
      }
    }
  `)

  const gamesDataHome = await graphql(`
    query SiteNavQuery {
      allStrapiGame(
        sort: { fields: creation_date, order: DESC }
        filter: {
          appid: {
            in: [
              "BigSword"
              "BoardTheTrain"
              "FireTheGun"
              "MergeGuns3D"
              "FeverRacing"
              "ColorBall3D"
              "ZombieSurvival"
              "CrazyMoto"
              "CrazyKart3D"
              "LetMeIn"
              "BumbleShooter"
              "Knife"
              "HiTaxi"
              "TrafficRun"
              "BulletMaster3D"
              "MrRacer"
              "MagicParkour"
              "FrozenMagic"
              "MrBullet"
              "JumpSmash"
              "CrazyKnife"
              "TrafficPassing"
              "SuperThrow"
              "AceMan"
              "BatterKing"
              "GoldenGlove"
              "KnockBalls"
              "CrashTower3D"
              "DragonCrush"
              "HungryAnimals"
              "SnakeGo"
              "DessertConnect"
              "SwiftRider"
              "CrackShot"
              "CrazyGunfight"
              "ColorRing"
              "PianoKeys"
              "ArchersKing"
              "MyBabyCare"
              "DartsKing3D"
              "CrazyRace"
              "BallIsComing"
              "HungyBunny"
              "TheSameWorld"
              "SuperMiner"
              "BounceShooter"
              "HillRacing"
              "BlockGun3D"
              "FruitMonster"
              "FierceCity"
              "IronAttack"
              "AirBrawl"
              "AmazingRoad"
              "RainbowSplash"
              "CrazyDrift"
              "FruitsFall"
              "RocketJump"
              "MagicPaint"
              "GlidingCharger"
              "RoadCharger"
              "ArcheryMaster"
              "UltraDrift"
              "SharkIsComing"
              "PuppyRun"
              "PenguinDash"
              "MonsterCrash"
              "DeathJump"
              "HungryMonster"
              "JumpingMonkey"
              "MergeKill"
              "CrazyTrain3D"
              "CrazyHammer"
              "VirusWar"
              "TrappedPirate"
              "StickmanVsZombies"
              "FingerCannon"
              "BulletMan"
              "GunShooter"
              "TowerBlast3D"
              "ShootSmash"
              "ShootingCubes"
              "BubbleBlast"
              "FlyPass"
              "KillAllZombies"
              "CollectColorfulBalls"
              "KimbapRun"
              "AnipopLink"
              "PetsMatch"
              "HappyBilliards"
              "CrazyBomb"
              "HelpTheZombie"
              "SaveThePets"
              "SoccerHero"
              "TableTennisChampionship"
              "MagicDonuts"
              "SolitaireClassic"
              "DeathRun"
              "IdleRestaurantTycoon"
              "ImEmpire"
              "MahjongConnect"
              "MiningMaster"
              "Transform"
              "DefenseTower"
              "TwistyRoad"
              "ZooBlast"
              "ZumaMarbles"
              "BlockPuzzle"
              "CrazyPortal"
              "DressQueen"
              "MahjongLink3D"
              "MergeAndDefense"
              "MergeMagicJewellery"
              "PetRun"
              "SkyRunning3D"
              "SuperGolf"
              "TowerDefenseX"
              "PandaRescue"
              "FillTheGlass"
              "MagicNumber"
              "PlantBeatZombies"
              "AirHockey3D"
              "MyBowling3D"
              "Chess3D"
              "8BallKing"
              "MyUnicorn"
              "MagicJigsaw"
              "FairyTalesPuzzle"
              "PipePuzzle"
              "SplittingCells"
              "FeedMaster"
              "FinalBattle"
              "SuperDefense"
              "Super2048"
              "BubblePop"
              "RelivedLife"
              "CandyHit"
              "MergeCat"
              "MelodyLink"
              "PuzzleVenture"
              "BrainMaster"
              "AntRun"
              "BombingTime"
              "BlockMaze"
              "HappyTetris"
              "MagicPainter"
              "MatchingCook"
              "ColorBead"
              "ColorSplash"
              "RollingAgent"
              "RushingRover"
            ]
          }
        }
      ) {
        nodes {
          icon_url
          title
          slug
          appid
          category {
            slug
            name
          }
        }
      }
    }
  `)

  const homeTemplatePath = path.resolve(`./src/templates/home.js`)
  const gameTemplatePath = path.resolve(`./src/templates/game.js`)
  const categoryTemplatePath = path.resolve(`./src/templates/category.js`)

  // const allGames = games.data.allStrapiGame.nodes
  const categories = allCategories.data.allStrapiCategory.nodes
  const dataHome = gamesDataHome.data.allStrapiGame.nodes
  const dataCategory = gamesDataCategory.data.allStrapiGame.nodes
  const dataDetail = gamesDataDetail.data.allStrapiGame.nodes

  // Home page
  createPage({
    path: `/`,
    component: homeTemplatePath,
    context: {
      games: dataHome,
      categories: categories,
    },
  })

  // Game Detail
  dataDetail.map(game => {
    createPage({
      path: `/game/${game.slug}`,
      component: gameTemplatePath,
      context: {
        // gid: game.gid,
        appid: game.appid,
      },
    })
  })

  // Category
  categories.map(category => {
    createPage({
      path: `/category/${category.slug}`,
      component: categoryTemplatePath,
      context: {
        category: category,
        games: dataCategory,
        categories: categories,
      },
    })
  })
}
